name = "devOS: Season 5"
author = "devOS: Sanity Edition"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bc46516c3a269e851ed0312cbf959c9cc504440b40a9390cfb4bef44443b07b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
