name = "devOS: Season 5"
author = "devOS: Sanity Edition"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a36eeadd2cf9c62fb41cf4e2b7329f9b1f0b1677b529b1c811beacceb7032926"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
